options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*'

# Rule Configuration
rules:
  brace-style:
    - 2
    -
      style: 'stroustrup'
      clean-import-paths: 2
  declarations-before-nesting: 2
  empty-args: 0
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  indentation:
    - 2
    -
      size: tab
  leading-zero:
    - 2
    -
      include: true
  mixin-name-format: 0
  nesting-depth: 0
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-misspelled-properties:
    - 2
    -
      extra-properties:
        - 'touch-callout'
        - 'overflow-scrolling'
  no-qualifying-elements: 0
  no-transition-all: 0
  no-vendor-prefixes: 1
  no-warn: 1
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  property-sort-order:
    - 2
    -
      order: smacss
  single-line-per-selector: 2
  shorthand-values: 1
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  trailing-semicolon: 2
  variable-name-format: 0
  zero-unit: 2
